# Generated by Django 4.2 on 2024-01-22 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200, unique=True)),
                ('language', models.CharField(blank=True, choices=[('de', 'German'), ('en-GB', 'British English'), ('es-ES', 'Spanish (Spain)'), ('fr', 'French'), ('it', 'Italian'), ('nl', 'Dutch'), ('pt-PT', 'Portuguese (Portugal)'), ('sv', 'Swedish'), ('da', 'Danish')], max_length=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('pms_hotel_id', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pms_reservation_id', models.CharField(blank=True, help_text='The reservation ID from the Property Management System', max_length=200, null=True)),
                ('pms_guest_id', models.CharField(blank=True, help_text='The guest ID from the Property Management System.\n        This is intended to be on Stay level, as the same person (phone) can stay in\n        multiple hotels with different guest IDs.', max_length=200, null=True)),
                ('status', models.CharField(choices=[('cancel', 'The guest has cancelled the reservation'), ('before', 'The guest has not checked in yet'), ('instay', 'The guest is currently in the hotel'), ('after', 'The guest has checked out'), ('unknown', 'The status is unknown')], default='unknown', max_length=50)),
                ('checkin', models.DateField(blank=True, null=True)),
                ('checkout', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stays', to='hotel.guest')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stays', to='hotel.hotel')),
            ],
            options={
                'unique_together': {('hotel', 'pms_reservation_id')},
            },
        ),
    ]
